DefaultContentLanguage = "zh"
dateFormat = "2006-01-02 15:04:05"
description = "ğŸŒ€riba2534's Blog"
enableEmoji = true
enableGitInfo = true
languageCode = "zh-cn"
theme = "diary"
title = "ğŸŒ€w0r1d's Blog"
baseURL = "https://cs-w0r1d.github.io/" 



[markup]
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = true
style = "github"
tabWidth = 4

[markup.goldmark.renderer]
unsafe = true

[params]
nableGitalk = true 
enableOpenGraph = true
enableTwitterCards = true

title = "ğŸŒ€w0r1d's Blog"
description = "w0r1dçš„ä¸ªäººæŠ€æœ¯åšå®¢ï¼Œåˆ†äº«ç¼–ç¨‹ã€æŠ•èµ„ã€ç”Ÿæ´»çš„æ€è€ƒä¸ç»éªŒ"
enableMathJax = true
enableLaTeX=true
enableReadingTime = true
favicon = "https://youke2.picui.cn/s1/2025/12/25/694cf29ad7de1.jpg"
subtitle = "å‡¡äº‹æœ‰äº¤ä»£ï¼Œä»¶ä»¶æœ‰ç€è½ï¼Œäº‹äº‹æœ‰å›éŸ³"

# twikooEnvId = "https://twikoo.riba2534.cn"
# enableTwikoo = true 

[params.gitalk]
owner = "cs-w0r1d"
repo = "cs-w0r1d.github.io"
client_id = "2535640"
client_secret = "Iv23liEhF8ZGGaTHWNdr"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"


[[menu.main]]
name = "æ–‡ç« ğŸ“–"
url = "/blog"
weight = 1

[[menu.main]]
name = "åˆ†ç±»ğŸ“Œ"
url = "/categories"
weight = 2

[[menu.main]]
name = "æ ‡ç­¾ğŸ·ï¸"
url = "/tags"
weight = 3

[[menu.main]]
name = "ç³»åˆ—ğŸ“š"
url = "/series"
weight = 4

[[menu.main]]
name = "å½’æ¡£ğŸ“ƒ"
url = "/archive"
weight = 5

[[menu.main]]
name = "å…³äºğŸ‘‹"
url = "/about"
weight = 6

[[menu.main]]
name = "å‹é“¾ğŸ”—"
url = "/friends"
weight = 7

[[menu.main]]
name = "RSSğŸ“¢"
url = "/index.xml"
weight = 8

[[menu.footer]]
name = "CSDN"
url = "https://blog.csdn.net/weixin_52083155"
weight = 1

[[menu.footer]]
name = "GitHub"
url = "https://github.com/cs-w0r1d"
weight = 2
[[menu.footer]]
name = "Zhihu"
url = "https://www.zhihu.com/people/W0R1D"
weight = 3

